// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MessageID.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from MessageID.proto</summary>
public static partial class MessageIDReflection {

  #region Descriptor
  /// <summary>File descriptor for MessageID.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static MessageIDReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg9NZXNzYWdlSUQucHJvdG8qigMKCVBLR1R5cGVJRBIcChhQS0dfU0VSVkVS",
          "X01FU1NBR0VfQkVHSU4QABIUChBQS0dfU0VSVkVSX1NUQVRFEAESFwoTUEtH",
          "X1NFUlZFUl9TSFVURE9XThACEh0KGVBLR19TRVJWRVJfR0FNRV9ST09NX0lO",
          "Rk8QChIkCiBQS0dfU0VSVkVSX05PVElGWV9VU0VSX0pPSU5fR0FNRRALEhsK",
          "FlBLR19TRVJWRVJfTUVTU0FHRV9NQVgQ5wcSFQoQUEtHX0dBTUVfVkVSU0lP",
          "ThDoBxIZChRQS0dfR0FURV9TRVJWRVJfTElTVBDpBxITCg5QS0dfR0FNRV9M",
          "T0dJThDrBxITCg5QS0dfR0FNRV9FUlJPUhDsBxIaChVQS0dfR0FNRV9BQ0NP",
          "VU5UX0lORk8Q7QcSEgoNUEtHX0dBTUVfSk9JThDMCBIUCg9QS0dfR0FNRV9D",
          "UkVBVEUQzQgSFwoSUEtHX0dBTUVfSk9JTl9JTkZPEM4IEhMKDlBLR19HQU1F",
          "X1NUQVJUENAPKnIKClNlcnZlclR5cGUSDAoIRVNUX05PTkUQABIWChJFU1Rf",
          "TUFOQUdFUl9TRVJWRVIQARIUChBFU1RfTE9CQllfU0VSVkVSEAISEwoPRVNU",
          "X0dBVEVfU0VSVkVSEAMSEwoPRVNUX0dBTUVfU0VSVkVSEAQq3QEKDUdhbWVF",
          "cnJvckNvZGUSDwoLR0VDX1NVQ0NFU1MQABIaChZHRUNfR0FNRV9WRVJTSU9O",
          "X0VSUk9SEAESFgoSR0VDX0lMTEVHQUxfQUNDRVNTEAISGgoWR0VDX0lOVkFM",
          "SURfTE9HSU5fVFlQRRADEhcKE0dFQ19JTlZBTElEX1VTRVJfSUQQBBIXChNH",
          "RUNfREVWSUNFX0lEX0VSUk9SEAUSFQoRR0VDX0lOVkFMSURfVE9LRU4QBhIi",
          "Ch5HRUNfTk9UX0xPR0lOX09SX0lOVkFMSURfVE9LRU4QByqFAQoJTG9naW5U",
          "eXBlEhEKDUVMVF9OT1RfTE9HSU4QABIYChRFTFRfTE9HSU5fQllfVklTSVRP",
          "UhABEhgKFEVMVF9MT0dJTl9CWV9BUFBMRUlEEAISGQoVRUxUX0xPR0lOX0JZ",
          "X0ZBQ0VCT09LEAMSFgoSRUxHX0xPR0lOX0JZX0dPT0xFEAQqQAoNVXNlckdh",
          "bWVTdGF0ZRINCglVR1NfUkVBRFkQABIPCgtVR1NfUExBWUlORxACEg8KC1VH",
          "U19ESVNDQVJEEAMqXAoJR2FtZVN0YXRlEgwKCEdTX1JFQURZEAASEAoMR1Nf",
          "SE9MRUNBUkRTEAESEAoMR1NfRkxPUENBUkRTEAISEQoNR1NfUklWRVJDQVJE",
          "UxADEgoKBkdTX0VORBAEKs0BCglDYXJkVHlwZXMSEQoNQ1RfSElHSFRfQ0FS",
          "RBAAEg8KC0NUX09ORV9QQUlSEAESEAoMQ1RfVFdPX1BBSVJTEAISFgoSQ1Rf",
          "VEhSRUVfT0ZfQV9LSU5EEAMSDwoLQ1RfU1RSQUlHSFQQBBIMCghDVF9GTFVT",
          "SBAFEhEKDUNUX0ZVTExfSE9VU0UQBhIVChFDVF9GT1VSX09GX0FfS0lORBAH",
          "EhUKEUNUX1NUUkFJR0hUX0ZMVVNIEAgSEgoOQ1RfUk9ZQUxfRkxVU0gQCWIG",
          "cHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::PKGTypeID), typeof(global::ServerType), typeof(global::GameErrorCode), typeof(global::LoginType), typeof(global::UserGameState), typeof(global::GameState), typeof(global::CardTypes), }, null));
  }
  #endregion

}
#region Enums
/// <summary>
///封包ID定义，1000以内为服务端专用，1000以外为服务端与客户端共用
///暂定每1000 为一个大块，做为功能分区，不同功能ID 定义在对应的区块内
/// </summary>
public enum PKGTypeID {
  [pbr::OriginalName("PKG_SERVER_MESSAGE_BEGIN")] PkgServerMessageBegin = 0,
  /// <summary>
  ///服务器状态信息
  /// </summary>
  [pbr::OriginalName("PKG_SERVER_STATE")] PkgServerState = 1,
  /// <summary>
  ///服务器关闭
  /// </summary>
  [pbr::OriginalName("PKG_SERVER_SHUTDOWN")] PkgServerShutdown = 2,
  /// <summary>
  ///游戏房间信息
  /// </summary>
  [pbr::OriginalName("PKG_SERVER_GAME_ROOM_INFO")] PkgServerGameRoomInfo = 10,
  /// <summary>
  ///通知游戏服务器有玩家加入
  /// </summary>
  [pbr::OriginalName("PKG_SERVER_NOTIFY_USER_JOIN_GAME")] PkgServerNotifyUserJoinGame = 11,
  [pbr::OriginalName("PKG_SERVER_MESSAGE_MAX")] PkgServerMessageMax = 999,
  /// <summary>
  ///游戏版本信息
  /// </summary>
  [pbr::OriginalName("PKG_GAME_VERSION")] PkgGameVersion = 1000,
  /// <summary>
  ///网关服务器列表
  /// </summary>
  [pbr::OriginalName("PKG_GATE_SERVER_LIST")] PkgGateServerList = 1001,
  /// <summary>
  ///进入游戏大厅
  /// </summary>
  [pbr::OriginalName("PKG_GAME_LOGIN")] PkgGameLogin = 1003,
  /// <summary>
  ///服务端报错
  /// </summary>
  [pbr::OriginalName("PKG_GAME_ERROR")] PkgGameError = 1004,
  /// <summary>
  ///帐户信息
  /// </summary>
  [pbr::OriginalName("PKG_GAME_ACCOUNT_INFO")] PkgGameAccountInfo = 1005,
  /// <summary>
  ///加入游戏
  /// </summary>
  [pbr::OriginalName("PKG_GAME_JOIN")] PkgGameJoin = 1100,
  /// <summary>
  ///创建游戏
  /// </summary>
  [pbr::OriginalName("PKG_GAME_CREATE")] PkgGameCreate = 1101,
  /// <summary>
  ///创建或加入游戏的信息
  /// </summary>
  [pbr::OriginalName("PKG_GAME_JOIN_INFO")] PkgGameJoinInfo = 1102,
  /// <summary>
  ///开始游戏
  /// </summary>
  [pbr::OriginalName("PKG_GAME_START")] PkgGameStart = 2000,
}

/// <summary>
///服务器类型
/// </summary>
public enum ServerType {
  [pbr::OriginalName("EST_NONE")] EstNone = 0,
  [pbr::OriginalName("EST_MANAGER_SERVER")] EstManagerServer = 1,
  [pbr::OriginalName("EST_LOBBY_SERVER")] EstLobbyServer = 2,
  [pbr::OriginalName("EST_GATE_SERVER")] EstGateServer = 3,
  [pbr::OriginalName("EST_GAME_SERVER")] EstGameServer = 4,
}

/// <summary>
///错误码
/// </summary>
public enum GameErrorCode {
  /// <summary>
  ///无错
  /// </summary>
  [pbr::OriginalName("GEC_SUCCESS")] GecSuccess = 0,
  /// <summary>
  ///版本错误
  /// </summary>
  [pbr::OriginalName("GEC_GAME_VERSION_ERROR")] GecGameVersionError = 1,
  /// <summary>
  ///非法访问
  /// </summary>
  [pbr::OriginalName("GEC_ILLEGAL_ACCESS")] GecIllegalAccess = 2,
  /// <summary>
  ///非法的登录方式
  /// </summary>
  [pbr::OriginalName("GEC_INVALID_LOGIN_TYPE")] GecInvalidLoginType = 3,
  /// <summary>
  ///错误的用户ID
  /// </summary>
  [pbr::OriginalName("GEC_INVALID_USER_ID")] GecInvalidUserId = 4,
  /// <summary>
  ///设备ID错误
  /// </summary>
  [pbr::OriginalName("GEC_DEVICE_ID_ERROR")] GecDeviceIdError = 5,
  /// <summary>
  ///令牌不合法
  /// </summary>
  [pbr::OriginalName("GEC_INVALID_TOKEN")] GecInvalidToken = 6,
  /// <summary>
  ///未登录或令牌错误
  /// </summary>
  [pbr::OriginalName("GEC_NOT_LOGIN_OR_INVALID_TOKEN")] GecNotLoginOrInvalidToken = 7,
}

/// <summary>
///登录方式
/// </summary>
public enum LoginType {
  /// <summary>
  ///未登录
  /// </summary>
  [pbr::OriginalName("ELT_NOT_LOGIN")] EltNotLogin = 0,
  /// <summary>
  ///游客登录
  /// </summary>
  [pbr::OriginalName("ELT_LOGIN_BY_VISITOR")] EltLoginByVisitor = 1,
  /// <summary>
  ///Apple登录
  /// </summary>
  [pbr::OriginalName("ELT_LOGIN_BY_APPLEID")] EltLoginByAppleid = 2,
  /// <summary>
  ///FaceBook登录
  /// </summary>
  [pbr::OriginalName("ELT_LOGIN_BY_FACEBOOK")] EltLoginByFacebook = 3,
  /// <summary>
  ///谷歌登录
  /// </summary>
  [pbr::OriginalName("ELG_LOGIN_BY_GOOLE")] ElgLoginByGoole = 4,
}

/// <summary>
///玩家的游戏状态
/// </summary>
public enum UserGameState {
  /// <summary>
  ///准备状态，并未加入游戏
  /// </summary>
  [pbr::OriginalName("UGS_READY")] UgsReady = 0,
  /// <summary>
  ///正在游戏
  /// </summary>
  [pbr::OriginalName("UGS_PLAYING")] UgsPlaying = 2,
  /// <summary>
  ///弃牌
  /// </summary>
  [pbr::OriginalName("UGS_DISCARD")] UgsDiscard = 3,
}

public enum GameState {
  /// <summary>
  ///准备状态，未开始游戏
  /// </summary>
  [pbr::OriginalName("GS_READY")] GsReady = 0,
  /// <summary>
  ///底牌
  /// </summary>
  [pbr::OriginalName("GS_HOLECARDS")] GsHolecards = 1,
  /// <summary>
  ///翻牌
  /// </summary>
  [pbr::OriginalName("GS_FLOPCARDS")] GsFlopcards = 2,
  /// <summary>
  ///河牌
  /// </summary>
  [pbr::OriginalName("GS_RIVERCARDS")] GsRivercards = 3,
  /// <summary>
  ///游戏结束，进入下一轮等待
  /// </summary>
  [pbr::OriginalName("GS_END")] GsEnd = 4,
}

public enum CardTypes {
  /// <summary>
  ///高牌
  /// </summary>
  [pbr::OriginalName("CT_HIGHT_CARD")] CtHightCard = 0,
  /// <summary>
  ///一对
  /// </summary>
  [pbr::OriginalName("CT_ONE_PAIR")] CtOnePair = 1,
  /// <summary>
  ///两对
  /// </summary>
  [pbr::OriginalName("CT_TWO_PAIRS")] CtTwoPairs = 2,
  /// <summary>
  ///三条
  /// </summary>
  [pbr::OriginalName("CT_THREE_OF_A_KIND")] CtThreeOfAKind = 3,
  /// <summary>
  ///顺子
  /// </summary>
  [pbr::OriginalName("CT_STRAIGHT")] CtStraight = 4,
  /// <summary>
  ///同花
  /// </summary>
  [pbr::OriginalName("CT_FLUSH")] CtFlush = 5,
  /// <summary>
  ///葫芦
  /// </summary>
  [pbr::OriginalName("CT_FULL_HOUSE")] CtFullHouse = 6,
  /// <summary>
  ///四条
  /// </summary>
  [pbr::OriginalName("CT_FOUR_OF_A_KIND")] CtFourOfAKind = 7,
  /// <summary>
  ///同花顺
  /// </summary>
  [pbr::OriginalName("CT_STRAIGHT_FLUSH")] CtStraightFlush = 8,
  /// <summary>
  ///皇家同花顺
  /// </summary>
  [pbr::OriginalName("CT_ROYAL_FLUSH")] CtRoyalFlush = 9,
}

#endregion


#endregion Designer generated code
